### PR TITLE
Add 5 dummy users to the SQL script (removed id from insert query)

### PR DESCRIPTION
**Pull request by vaibhavbansal23**
for issue #21

### CODE REVIEW

**Comment by murzeus** [comment]
@vaibhavbansal23 this is great but as I can see you are creating a new file to add data and old file has been moved to a new file, can you edit the existing file without creating a new file? (you can update this PR without creating another one)

**Comment by vaibhavbansal23** [comment]
done !!

**Comment by murzeus** [comment]
@vaibhavbansal23 great, there is one small change you need to do before merging. If you look closely you can see the filed `id` is set to `AUTO_INCREMENT` so no need to provide an `id`.

**Comment by vaibhavbansal23** [comment]
done !!

**Pull request merged**
